<a href="https://colab.research.google.com/github/bhavya-samboju/2311CS020589/blob/main/ad1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[2,12,23,10,89]])
print(arr)
print('0th element on 2nd row: ', arr[2,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2 12 23 10 89]]
0th element on 2nd row:  89
